package com.example.GestionPlanAction.dto;

import java.math.BigInteger;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExerciseDTO {
	
	

	
	private Long id;
	private Integer annee;
	private Boolean verrouille;

	// Getters and Setters can be generated by Lombok
	// No need to manually write them if using @Data annotation
}
